### Publish some values to the MQTT broker ###
#  to be picked up by an MQTT subscriber
  - alias: 'Publish Commute time'
    trigger:
      - platform: time
        minutes: 1
    action:
      - service: mqtt.publish
        data_template:
          topic: 'commute/to_work/JF'
          payload: '{{ states("sensor.jf_morning_commute") }}'
### TURN ON THE LIGHTS AROUND SUNSET
  - alias: 'Light on Sunset'  
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:30:00"
      - platform: time
        at: '17:00'
    action:
        service: homeassistant.turn_on
        entity_id: 
        - switch.porch_lights_switch
        - light.hall_light
### TURN OFF THE LIGHTS AT SUNRISE
  - alias: 'Light off Sunrise'  
    trigger:
      - platform: sun
        event: sunrise
        offset: "-00:10:00"
      # - platform: time
        # at: '7:30'
    action:
       service: homeassistant.turn_off
       entity_id: 
        - switch.porch_lights_switch

### OTHER AUTOMATIONS

  # - alias: 'Shed light on motion'
    # trigger:
      # - platform: state
        # entity_id: binary_sensor.shed_motion
        # from: 'off'
        # to: 'on'
    # condition: 
      # condition: and
      # conditions:
        # - condition: sun
          # after: sunset
          # after_offset: "-0:30:00"
        # - condition: sun
          # before: sunrise
          # before_offset: "-0:30:00"
        # - condition: state
          # entity_id: sun.sun
          # state: 'below_horizon'

    # action:
      # - service: homeassistant.turn_on
        # entity_id: switch.shed_light_switch

  # - alias: 'Shed light off motion with delay'
    # trigger:
      # platform: state
      # entity_id: switch.shed_light_switch
      # from: 'off'
      # to: 'on'
      # for:
        # minutes: 10
    # action:
      # - service: homeassistant.turn_off
        # entity_id: switch.shed_light_switch
  # - alias: 'Shed motion detected'
    # trigger:
      # platform: mqtt
      # topic: sensor/shed/motion
      # payload: 1
    # action:
      # - service: notify.mypushbullet
        # data_template: 
          # message: "There was motion in the shed"

  # - alias: 'Shed battery monitor'
    # trigger:
      # platform: numeric_state
      # entity_id: sensor.shed_battery
      # below: 50
      # for:
       # hours: 1
    # action:
      # - service: notify.mypushbullet
        # data_template: 
          # message: "The shed node battery is low"
#################################################################
## HASS Related
#################################################################
### CONFIGURE FRONTEND THEMES
  - alias: 'Set theme at startup'
    initial_state: 'on'
    trigger:
     - platform: homeassistant
       event: start
    action:
      service: frontend.set_theme
      data:
        name: darkcyan
  - alias: 'Set dark theme for the night'
    initial_state: True
    trigger:
      - platform: time
        at: '21:00'
    action:
      - service: frontend.set_theme
        data:
          name: darkred
  - id: change_current_theme
    alias: 'Change Current Theme'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.current_theme
    action:
      - service: frontend.set_theme
        data_template:
          name: '{{states.input_select.current_theme.state}}'
  - alias: Update notifications
    trigger:
     - platform: state
       entity_id: updater.updater
    action:
     - service: notify.mypushbullet
       data_template: 
         message: "Home Assistant  {{ states.updater.updater.state }}  is now available."
### HEAL ZWAVE NETWORK DAILY
  - id: heal_zwave_network
    alias: Heal Z-Wave Network
    initial_state: 'off'
    trigger:
      platform: time
      at: '12:31:00'
    action:
     - service: zwave.heal_network
       data_template: 
         message: "zwave nework healed."
