homeassistant:
  # Name of the location where Home Assistant is running
  name: MyHome
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Customization file
  #customize: !include_dir_merge_named customizations
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
#history:

# View all events in a logbook
#logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google
zwave:
   usb_path: /dev/ttyACM0
   network_key: !secret zwave_ntwk_key
emulated_hue: !include hue.yaml
notify:
  - name: simple_notifier
    platform: pushbullet
    api_key: !secret pushbullet_token
 ### INCLUDES ###
# armcrest: !include armcrest.yaml
# lights: !include lights.yaml
# climate: !include climate.yaml
frontend: !include frontend.yaml
automation: !include automation.yaml
camera: !include camera.yaml
device_tracker: !include device_tracker.yaml
group: !include group.yaml 
mqtt: !include mqtt.yaml
#notify: !include notify.yaml
script: !include script.yaml
sensor: !include sensor.yaml
switch: !include switch.yaml
weblink: !include weblink.yaml
wemo: !include wemo.yaml
zone: !include zone.yaml
