homeassistant:
  # Name of the location where Home Assistant is running
  name: MyHome
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Customization file
  customize: !include customize.yaml
# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
#history:
# View all events in a logbook
#logbook:
logger:
  default: error
# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

zwave:
   usb_path: /dev/ttyACM0
   network_key: !secret zwave_ntwk_key
   autoheal: false
emulated_hue: !include hue.yaml

notify:
  - name: mypushbullet
    platform: pushbullet
    api_key: !secret pushbullet_token

### INCLUDES ###
# lights: !include lights.yaml
# climate: !include climate.yaml
# climate: !include_dir_list climate.yaml
amcrest: !include amcrest.yaml
binary_sensor: !include binary_sensor.yaml
automation: !include automation.yaml
camera: !include camera.yaml
device_tracker: !include device_tracker.yaml
frontend: !include frontend.yaml
group: !include group.yaml 
lyric: !include lyric_t5.yaml
mqtt: !include mqtt.yaml
scene: !include scenes.yaml
script: !include script.yaml
sensor: !include sensor.yaml
switch: !include switch.yaml
weblink: !include weblink.yaml
wemo: !include wemo.yaml
zone: !include zone.yaml
